### ISSUE TITLE
Boxsize should be locked while working

### ISSUE THREAD

**Issue by derula** [hkociemba/sudokuNxM#1]
Hi, cool program, I've recently been fiddling a bit with a grid generator of my own, I based it on [this](http://forum.enjoysudoku.com/giant-sudoku-s-16x16-25x25-36x36-100x100-t6578-120.html#p259504) general algorithm you described, but added some heuristics and things to it to make it faster, with... mild success :)

I've been using your tool a bit to reduce the puzzles I generated, and noticed that you can change the grid size while reduction is in progress, with various hilarious results such as:

- The program freezes completely
- SAT removes all but 2 givens (they were in the same row... and also the same number somehow)
- Access violations
- Otherwise unexpected behavior.

Maybe these buttons should be disabled while work is in progress :)

Cheers and have a good one! And thanks for describing that algorithm in that forum that one time, it clued me in on how to get started! (Though I eventually gave up waiting for the 32x32 boxsize grid to complete and used a shuffled default grid instead, lol)

**Comment by hkociemba** [comment]
Sorry, I did not notice your issue earlier. I did some code modifications and hope it works better now.
